// Generated by Wrangler by running `wrangler types`

interface Env {
	TRUESTED_HOSTS: string[];
	IMAGE_SOURCE: R2Bucket;
	CACHE_MAX_AGE?: number; // Cache duration in seconds, default: 31536000 (1 year)
}
